services:
  directoryms:
    build:
      context: .
      dockerfile: DirectoryMS/Dockerfile
    container_name: directoryms_api
    environment:
      ConnectionStrings__DefaultConnection: "Server=sql_server,1433;Database=DIRECTORY;User Id=sa;Password=SecurePassword123!;TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "8081:8080"
    networks:
      - cuidarmed_new_net

networks:
  cuidarmed_new_net:
    external: true